PROJECT=Gopher_Concurrency_Exercises

GENERATED_EXECUTABLES=bin/$(LC_PROJECT)-demo \
                      bin/daily_walk \
                      bin/eating_tapas-run \
                      bin/internet_café

GENERATED_SOURCES=

SCRIPTS=

TEST_OUTPUT=tests/results

